{% set name = "quartodoc" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quartodoc-{{ version }}.tar.gz
  sha256: fe94d373f11a640a020f42a94f857d95dfcd1bb2c3fe7db1923af5be124eab8f

build:
  entry_points:
    - quartodoc = quartodoc.__main__:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.10
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.10
    - click
    - griffe >=0.33
    - sphobjinv >=2.3.1
    - tabulate >=0.9.0
    - importlib-metadata >=5.1.0
    - importlib-resources >=5.10.2
    - pydantic
    - pyyaml
    - requests
    - typing-extensions >=4.4.0
    - watchdog >=3.0.0
    - plum-dispatch >2.0.0

test:
  imports:
    - quartodoc
  commands:
    - pip check
    - quartodoc --help
  requires:
    - pip

about:
  home: https://github.com/machow/quartodoc
  summary: Generate API documentation with Quarto.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
