{% set name = "quartodoc" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quartodoc-{{ version }}.tar.gz
  sha256: 1f287891773bd86ab84cfa1d55181e03e4bf74d57035c73dc1c0e7355148ad27

build:
  entry_points:
    - quartodoc = quartodoc.__main__:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.10
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - typing_extensions >=4.4.0
    - python >=3.10
    - black
    - click
    - griffe >=0.33
    - sphobjinv >=2.3.1
    - tabulate >=0.9.0
    - importlib-metadata >=5.1.0
    - importlib-resources >=5.10.2
    - pydantic
    - pyyaml
    - requests
    - typing-extensions >=4.4.0
    - watchdog >=3.0.0
    - plum-dispatch >2.0.0

test:
  imports:
    - quartodoc
  commands:
    - pip check
    - quartodoc --help
  requires:
    - pip

about:
  home: https://github.com/machow/quartodoc
  summary: Generate API documentation with Quarto.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
