{% set python_min = '3.10' %}
{% set name = "quartodoc" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quartodoc-{{ version }}.tar.gz
  sha256: 418d9ff0f2d4481a87e926e3a3e5bc31efbe556c7f36912aa0a3f716c0eafa9c

build:
  entry_points:
    - quartodoc = quartodoc.__main__:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - typing_extensions >=4.4.0
    - python >={{ python_min }}
    - black
    - click
    - griffe >=0.33
    - sphobjinv >=2.3.1
    - tabulate >=0.9.0
    - importlib-metadata >=5.1.0
    - importlib-resources >=5.10.2
    - pydantic
    - pyyaml
    - requests
    - typing-extensions >=4.4.0
    - watchdog >=3.0.0
    - plum-dispatch >2.0.0

test:
  imports:
    - quartodoc
  commands:
    - pip check
    - quartodoc --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/machow/quartodoc
  summary: Generate API documentation with Quarto.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gforsyth
